export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_ERROR = 'GET_CITIES_ERROR';

export const CHANGE_FAVORITE = 'CHANGE_FAVORITE';

export const Action = {
  GET_CITIES_REQUEST,
  GET_CITIES_SUCCESS,
  GET_CITIES_ERROR,
  CHANGE_FAVORITE,
};
